### PR TITLE
Adding support for multiple compose files using env vars #90

### PR DESCRIPTION
**Pull request by davenuman**

### CODE REVIEW

**Comment by billwanjohi** [comment]
This appears to have been a breaking change, making it no longer possible to run aliases from subdirectories. AEFLA dev procedures relied on this older behavior, and now have to be altered.

**Comment by davenuman** [comment]
@billwanjohi not sure how this could have broke for your project. My guess is that now that bowline mimics the behavior of docker-compose and includes docker-compose.override.yml by default, there might be something in that file that is changing your config unexpectedly.  
This section of the readme might be helpful:
https://github.com/CivicActions/bowline#working-with-docker-compose

**Comment by billwanjohi** [comment]
@davenuman this might be easier to just demonstrate:

```
cabill in aefla.ed.gov/html/themes on  master [!]
❯ docker-compose images
WARNING: The UID variable is not set. Defaulting to a blank string.
           Container                                   Repository                         Tag       Image Id       Size
-------------------------------------------------------------------------------------------------------------------------
aeflaedgov_base_1                 <none>                                                 <none>   93f2a792f1cd   667.3 MB
aeflaedgov_cli_1                  <none>                                                 <none>   f74057c6e19c   669.4 MB
aeflaedgov_cli_run_44cc7a03e357   registry.civicactions.net/lincs/aefla.ed.gov/web-dev   latest   386f35ea7e52   671.8 MB
aeflaedgov_cypress_1              <none>                                                 <none>   2708c638956e   2.201 GB
aeflaedgov_db_1                   registry.civicactions.net/lincs/aefla.ed.gov/db        latest   b5b41b4e7d32   399.4 MB
aeflaedgov_node_1                 <none>                                                 <none>   9d8f5d6949df   941.6 MB
aeflaedgov_web_1                  registry.civicactions.net/lincs/aefla.ed.gov/web-dev   latest   386f35ea7e52   671.8 MB

cabill in aefla.ed.gov/html/themes on  master [!]
❯ COMPOSE_FILE=docker-compose.yml docker-compose images
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.yml'
```

This example is trivial, but imagine I am running something that cares about its current working directory.

The issue is that the default behavior of docker-compose is to traverse the file path looking for a file named `docker-compose.yml`, and projects initialized before this change may have (and in the case of AEFLA _did_) start to rely on that behavior. Our devs expect to be able to run the aliased commands wherever they are in the repository, and that was short-circuited by specifying a list of paths.

That doesn't necessarily mean that we should revert this, but it's important to understand that it can (and in our case did) break existing procedures.

**Comment by davenuman** [comment]
I see what you mean now. After reviewing the code I haven't decided on an approach yet. Perhaps we can add a parameter (or by default) set the COMPOSE_FILE to use an absolute path so that it will work in other directories.

As a workaround for now, I created a docker tag which has the new code reverted:
https://hub.docker.com/layers/civicactions/bowline/single-compose-file/images/sha256-a75fd69d6af3c20fe635a7147654613b5bb8e3c5953f40be82b5ae1639c3860a

**Pull request merged**
